### ISSUE TITLE
"View Code" button doesn't work

### ISSUE THREAD

**Issue by JosephTLyons** [Alhadis/language-emacs-lisp#4]
Not sure what the issue is (if its on my end or a fault of the package), but clicking "view code" in this package's settings does not launch a new instance of atom with the code for this package, as it should.  I think this is the only package of mine that has this issue, but I can't conclude where the fault is.

I'm on:
macOS v10.13.6
Atom v1.30.0
language-emacs-lisp v1.3.0

**Comment by Alhadis** [comment]
If you're trying to open the CSON file for the Elisp grammar, it... could take a while. Atom has serious performance issues whenever that grammar is opened, likely because of the size.

**Comment by JosephTLyons** [comment]
I'm not sure.  It doesn't seem to open at all.  Maybe something is timing out with Atom.  Not a big deal at all, I can open the file manually by going in to the package folder.

**Comment by Alhadis** [comment]
You're better off reporting this upstream to the [`atom/settings-view`](https://github.com/atom/settings-view) repository. There could also be additional clues in the developer console (like a error message or something), but since the button's working fine for me, I'm assuming this is a site-specific issue.

Closing this as there's really nothing I can do.
