### ISSUE TITLE
Muse: do not allow newlines after opening and before closing "*"

### ISSUE THREAD

**Issue by link2xt** [Alhadis/language-emacs-lisp#5]
This should not be highlighted as emphasized:

```
*
foo bar*
```

This is unclosed emphasis:
```
*foo bar
*
```

**Comment by Alhadis** [comment]
This is actually impossible to fix due to the limitations of the TextMate grammar system. It processes documents one line at a time, which means something like this:

```
foo *bar
*
```

is impossible to differentiate from this:

```
foo *bar
baz*
```

I could prevent a lone `*` from *starting* an emphasised text run, however:

```regexp
/^\*$/
```

**Comment by link2xt** [comment]
I have it fixed in `language-muse`, this spec passes:
https://github.com/link2xt/atom-muse/blob/ea85da13a26cd89876ef2bd1ba4bfd3fd7f68f50/spec/muse-spec.coffee#L72-L80

My emphasis parsing is here:
https://github.com/link2xt/atom-muse/blob/ea85da13a26cd89876ef2bd1ba4bfd3fd7f68f50/grammars/muse.cson#L69-L85

**Comment by Alhadis** [comment]
Yes, that's because Atom recently changed their highlighting-engine to support newlines. However, other TextMate-grammar implementations don't support this (notably GitHub's).

You can see for yourself:

* [`*\nFoo Bar*`](https://github-lightshow.herokuapp.com/?utf8=✓&scope=from-url&grammar_format=cson&grammar_url=https%3A%2F%2Fgithub.com%2Flink2xt%2Fatom-muse%2Fblob%2Fea85da13a26cd89876ef2bd1ba4bfd3fd7f68f50%2Fgrammars%2Fmuse.cson&grammar_text=&code_source=from-text&code_url=&code=*%0D%0AFoo+Bar*)
* [`*Foo bar\n* baz*`](https://github-lightshow.herokuapp.com/?utf8=✓&scope=from-url&grammar_format=cson&grammar_url=https%3A%2F%2Fgithub.com%2Flink2xt%2Fatom-muse%2Fblob%2Fea85da13a26cd89876ef2bd1ba4bfd3fd7f68f50%2Fgrammars%2Fmuse.cson&grammar_text=&code_source=from-text&code_url=&code=*Foo+bar%0D%0A*+baz*)

**Comment by link2xt** [comment]
> You can see for yourself:
> ...

First example works correctly, the second I just fixed:
https://github.com/link2xt/atom-muse/commit/0a728c9e918f0ba90406cf5c2c1d635d27e2cc98

Now both examples work correctly on https://github-lightshow.herokuapp.com/

**Comment by Alhadis** [comment]
What about this?

~~~
*foo bar
* baz
~~~

[Lightshow](https://github-lightshow.herokuapp.com/?utf8=✓&scope=from-url&grammar_format=cson&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Flink2xt%2Fatom-muse%2F0a728c9e918f0ba90406cf5c2c1d635d27e2cc98%2Fgrammars%2Fmuse.cson&grammar_text=&code_source=from-text&code_url=&code=*foo+bar%0D%0A*+baz) is tokenising it as

~~~html
<pre class="code"><span class="pl-mi">*foo bar</span>
<span class="pl-mi">* baz</span>
</pre>
~~~

... but Pandoc gives me:

~~~html
<p>*foo bar</p>
<h1 id="baz">baz</h1>
~~~

**Comment by link2xt** [comment]
This markup is invalid because `*` is not closed, so I am not sure here. Pandoc also gives this:
```
$ pandoc -f muse -t native
*foo bar
----
baz*
[Para [Emph [Str "foo",Space,Str "bar",SoftBreak,Str "----",SoftBreak,Str "baz"]]]
```

Generally speaking, any block markup should break paragraphs, and it is better to parse it as 
```
[Para [Str "*foo",Space,Str "bar"]
,HorizontalRule
,Para [Str "baz*"]]
```
because otherwise we can't determine if the second line is a block or not without parsing the third line. Pandoc implementation does backtracking which may be quite expensive in extreme cases, like lots of nested unclosed tags.

In `muse.cson` emphasis consumes more than it should because I do not parse paragraphs beforehand, it is a bug.

**Comment by link2xt** [comment]
Alternatively, it can be treated as a part of inline markup, even if there is no closing `*`. In other workds, unclosed inline markup is undefined behavior.

**Comment by Alhadis** [comment]
How should this be treated?

~~~
Foo **bold**bar baz qux** qul
~~~

The `Text::Amuse` wiki [says](https://amusewiki.org/library/manual#toc40):

> The opening one must be preceded by something which is not an alphanumerical character (or at the beginning of the line) and ***followed by something which is not a space***.

This means that the code above should be rendered like this:

~~~html
<p>Foo *<em>boldbar baz qux</em>* qul</p>
~~~

But, wouldn't it be more natural to render it like this...?

~~~html
<p>Foo <strong><em>boldbar baz qux</em></strong> qul</p>
~~~

**Comment by link2xt** [comment]
I think it should be
```html
<p>Foo <strong>bold**bar baz qux</strong> qul</p>
```

Text::Amuse produced this:
```html
<p>
Foo <strong>bold**bar baz qux</strong> qul
</p>

```

**Comment by link2xt** [comment]
Pandoc is fixed, now it produces
```html
<p>Foo <strong>bold**bar baz qux</strong> qul</p>
```

**Comment by Alhadis** [comment]
Is there a painless way to run an up-to-date `Text::Amuse` from command-line? [`muse-quick.pl` is deprecated](https://github.com/melmothx/text-amuse/blob/3e18b5184da262d96e7d3165fbbe48ceae419ee3/bin/muse-quick.pl#L52-L53) and installing `Text::Amuse::Compile` is proving to be a pain-in-the-arse due to this shitty MacBook's crippled build system (I don't know what the previous owner did to it, but anything relying on a C compiler is broken...).

All I need is the raw HTML output, I don't give a crap about EPUB or LaTeX, so there's a million CPAN dependencies I don't need which are probably adding to the installation grief.

**Comment by link2xt** [comment]
You can use this script prepared for GitHub markup repository:
https://github.com/link2xt/markup/blob/muse/lib/github/commands/muse2html

**Comment by Alhadis** [comment]
[Lol, too late](https://github.com/Alhadis/language-emacs-lisp/tree/54f489bbf2d4251b826d0a71659c7022b2737dd0/spec/tools).

Thanks anyway though. 😅

**Comment by Alhadis** [comment]
Okay, I *think* I've fixed the emphasis matching. Could I get you to update your branch locally and tell me if there's anything I've missed?

Bear in mind there's nothing we can do about this:

~~~
Foo *italic*unclosed italic
~~~

Which for all intents and purposes, is the same thing as:

~~~
Foo *italic*unclosed italic
bar* baz
~~~
